server:
  port: 8088
  servlet:
    context-path: /dockerizer-app

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}/?retryWrites=true&w=majority
      database: ${MONGODB_DATABASE}
